# Generated by Django 5.2.12 on 2026-03-12 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="配队名称")),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "axis_length",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="轴长 (秒)"
                    ),
                ),
                (
                    "dps",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="DPS (万分之一)"
                    ),
                ),
                (
                    "matrix_score",
                    models.IntegerField(blank=True, null=True, verbose_name="矩阵分数"),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("简单", "简单"), ("中等", "中等"), ("困难", "困难")],
                        default="中等",
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        default="通用", max_length=50, verbose_name="适配环境"
                    ),
                ),
                (
                    "contributors",
                    models.CharField(
                        default="mozz", max_length=200, verbose_name="贡献者"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "配队",
                "verbose_name_plural": "配队",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RotationAxis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="轴名称")),
                (
                    "video_url",
                    models.CharField(
                        blank=True, max_length=500, null=True, verbose_name="视频 URL"
                    ),
                ),
                (
                    "total_duration",
                    models.IntegerField(default=30, verbose_name="总时长 (秒)"),
                ),
                (
                    "segments_data",
                    models.JSONField(default=dict, verbose_name="时间轴数据"),
                ),
                ("characters", models.JSONField(default=list, verbose_name="角色列表")),
                ("order", models.IntegerField(default=0, verbose_name="顺序")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="axes",
                        to="api.team",
                        verbose_name="配队",
                    ),
                ),
            ],
            options={
                "verbose_name": "输出轴",
                "verbose_name_plural": "输出轴",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="TeamCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.IntegerField(verbose_name="角色 ID")),
                (
                    "character_name",
                    models.CharField(max_length=50, verbose_name="角色名称"),
                ),
                (
                    "energy",
                    models.CharField(
                        blank=True, default="", max_length=10, verbose_name="充能需求"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="顺序")),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_characters",
                        to="api.team",
                        verbose_name="配队",
                    ),
                ),
            ],
            options={
                "verbose_name": "配队角色",
                "verbose_name_plural": "配队角色",
                "ordering": ["order"],
            },
        ),
    ]
